### ISSUE TITLE
Manual Install problems

### ISSUE THREAD

**Issue by gjnave** [pinokiofactory/cogstudio#1]
there some problems with the manual install that Ive noticed:
1) "File not found" for the 5b models.. it seems in [app.py](http://app.py/) you are using a link to your own machine and forgot to remove it
2) [cogstudio.py](http://cogstudio.py/) doesnt exist.. im assuming you renamed it to [app.py](http://app.py/)
3) Im uncertain what these directions mean:
"Next copy the [cogstudio.py](https://github.com/pinokiofactory/cogstudio/blob/main/cogstudio.py) under the CogVideo/inference/gradio_composite_demo folder."
copy it to where?
4) after making changes to #1, the app loads but its the old CogVideo demo

**Comment by CannibalKush** [comment]
The install instructions are kind of weird.

The secret missing step is that it's expected of you to copy this repo's [cogstudio.py](https://raw.githubusercontent.com/pinokiofactory/cogstudio/refs/heads/main/cogstudio.py) to 'CogVideo\inference\gradio_composite_demo'
